name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        echo VUE_APP_REST_API_URL="http://node3.blackseachain.com:4444" >> .env
        cat .env
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag avalanche-explorer-web-app:$(date +%s)
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/avalanche-explorer-web-app:$(date +%s)
